name: Jupyter notebook

on: 
  pull_request:
    paths:
      - '**.ipynb'
  push:
    paths:
      - '**.ipynb'
jobs:
    clean_and_databricks:
      name: clean output and generate databricks
      runs-on: ubuntu-latest
      steps:
      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
      - name: Convert Jupyter Notebooks to Databricks Notebooks
        uses: rafaelvp-db/jupyter-to-databricks@v1.3
        with:
        # Relative path to the folder containing Jupyter notebooks
          inputPath: ./ai_analysis
      # Relative path to the folder to which DB notebooks will be output
          outputPath: ./ai_analysis/datablock
